# Default Profile
[profile.default]
evm_version = "shanghai"
ffi = false
fs_permissions = [{ access = "read-write", path = "./"}]
fuzz_runs = 256
optimizer = true
optimizer_runs = 1_000_000
remappings = [
  "@chainlink=lib/chainlink/contracts/src/v0.8/",
  "@solidstate/contracts/=lib/solidstate-solidity/contracts/",
  "forge-safe/=lib/forge-safe/src/",
  "forge-std/=lib/forge-std/src/",
]
solc_version = '0.8.19'
src = "contracts"
verbosity = 1

# CI Profile
[profile.CI]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
arb_fork_tenderly = "${PERP_MINT_ARB_URL}"
arbitrum-one = "${ARBITRUM_RPC_URL}"
arbitrum-goerli = "${ARBITRUM_GOERLI_RPC_URL}"
base = "${BASE_RPC_URL}"
base-goerli = "${BASE_GOERLI_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum-goerli = { key = "${ARBISCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base-goerli = { key = "${BASESCAN_API_KEY}" }
