# Default Profile
[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1_000_000
remappings = [
  "@solidstate/=lib/solidstate-solidity/contracts/",
  "@solidstate/layerzero-client/=lib/layerzero-client/contracts/",
  "forge-std/=lib/forge-std/src/"
]
verbosity = 1

# CI Profile
[profile.CI]
fuzz_runs = 100_000
verbosity = 4
